try{
    hello()
}catch(err){
    console.log(err)
}

try{
    anotherFunction()

}catch{
    console.log('text did not passed')
}